name: Build and Update Container Image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: homolog

    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1

      - uses: actions/setup-java@v2  
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: java-version

      - name: Cache Maven packages
        uses: action/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2 

      - name: Build Maven package
        run: mvn --batch-mode --update-snapshots package                
        working-directory: backend
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

      - name: Update container image
        run: echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USER" --password-stdin
        run: docker build -t dscatalog:latest .
        run: docker tag dscatalog:latest $DOCKERHUB_USER/dscatalog:latest;
        run: docker push $DOCKERHUB_USER/dscatalog; 
        working-directory: backend

      - run: echo "done build project and upload container image"