name: Deploy on Dokku

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: homolog

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      APP_HOST_DOKKU: ${{ secrets.APP_HOST_DOKKU }}

    steps:
      - name: Cloning repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: idoberko2/dokku-deploy-github-action@v1               
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: $APP_HOST_DOKKU
          app-name: 'dscatalog-v3'
          git-push-flags: '--force'
          working-directory: backend          
