name: Deploy on Dokku

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: homolog

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      APP_HOST_DOKKU: ${{ secrets.APP_HOST_DOKKU }}

    steps:
      - name: Cloning repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@v1.1.3                
        with:
          git_remote_url: 'ssh://dokku@$APP_HOST_DOKKU.me:22/dscatalog-v3'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
